[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
check_untyped_defs = true
strict_optional = true

[tool.bandit]
skips = ["B101"]
