[
  {"cpt": "0001A", "icd": "A00.1"},
  {"cpt": "0002A", "icd": "B00.2"},
  {"cpt": "0003A", "icd": "C00.3"},
  {"cpt": "0004A", "icd": "D00.4"},
  {"cpt": "0005A", "icd": "E00.5"},
  {"cpt": "0006A", "icd": "F00.6"},
  {"cpt": "0007A", "icd": "G00.7"},
  {"cpt": "0008A", "icd": "H00.8"},
  {"cpt": "0009A", "icd": "I00.9"},
  {"cpt": "0010A", "icd": "J00.10"}
]
